# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/bosilca/unstable/tesse/parsec-cxx

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/bosilca/unstable/tesse/parsec-cxx

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"flow\" \"ttg-mad\" \"ttg-parsec\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bosilca/unstable/tesse/parsec-cxx/CMakeFiles /Users/bosilca/unstable/tesse/parsec-cxx/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/bosilca/unstable/tesse/parsec-cxx/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ttgtest-parsec

# Build rule for target.
ttgtest-parsec: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ttgtest-parsec
.PHONY : ttgtest-parsec

# fast build rule for target.
ttgtest-parsec/fast:
	$(MAKE) -f CMakeFiles/ttgtest-parsec.dir/build.make CMakeFiles/ttgtest-parsec.dir/build
.PHONY : ttgtest-parsec/fast

#=============================================================================
# Target rules for targets named mxm-summa-mad

# Build rule for target.
mxm-summa-mad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mxm-summa-mad
.PHONY : mxm-summa-mad

# fast build rule for target.
mxm-summa-mad/fast:
	$(MAKE) -f CMakeFiles/mxm-summa-mad.dir/build.make CMakeFiles/mxm-summa-mad.dir/build
.PHONY : mxm-summa-mad/fast

#=============================================================================
# Target rules for targets named t9-wrap

# Build rule for target.
t9-wrap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t9-wrap
.PHONY : t9-wrap

# fast build rule for target.
t9-wrap/fast:
	$(MAKE) -f CMakeFiles/t9-wrap.dir/build.make CMakeFiles/t9-wrap.dir/build
.PHONY : t9-wrap/fast

#=============================================================================
# Target rules for targets named ttgtest-mad

# Build rule for target.
ttgtest-mad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ttgtest-mad
.PHONY : ttgtest-mad

# fast build rule for target.
ttgtest-mad/fast:
	$(MAKE) -f CMakeFiles/ttgtest-mad.dir/build.make CMakeFiles/ttgtest-mad.dir/build
.PHONY : ttgtest-mad/fast

#=============================================================================
# Target rules for targets named t9

# Build rule for target.
t9: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t9
.PHONY : t9

# fast build rule for target.
t9/fast:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/build
.PHONY : t9/fast

#=============================================================================
# Target rules for targets named helloworld

# Build rule for target.
helloworld: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld
.PHONY : helloworld

# fast build rule for target.
helloworld/fast:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/build
.PHONY : helloworld/fast

#=============================================================================
# Target rules for targets named mxm_simple_suma

# Build rule for target.
mxm_simple_suma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mxm_simple_suma
.PHONY : mxm_simple_suma

# fast build rule for target.
mxm_simple_suma/fast:
	$(MAKE) -f CMakeFiles/mxm_simple_suma.dir/build.make CMakeFiles/mxm_simple_suma.dir/build
.PHONY : mxm_simple_suma/fast

#=============================================================================
# Target rules for targets named helloworld_wrap

# Build rule for target.
helloworld_wrap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 helloworld_wrap
.PHONY : helloworld_wrap

# fast build rule for target.
helloworld_wrap/fast:
	$(MAKE) -f CMakeFiles/helloworld_wrap.dir/build.make CMakeFiles/helloworld_wrap.dir/build
.PHONY : helloworld_wrap/fast

#=============================================================================
# Target rules for targets named t9-wrap-mad

# Build rule for target.
t9-wrap-mad: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 t9-wrap-mad
.PHONY : t9-wrap-mad

# fast build rule for target.
t9-wrap-mad/fast:
	$(MAKE) -f CMakeFiles/t9-wrap-mad.dir/build.make CMakeFiles/t9-wrap-mad.dir/build
.PHONY : t9-wrap-mad/fast

helloworld.o: helloworld.cc.o

.PHONY : helloworld.o

# target to build an object file
helloworld.cc.o:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/helloworld.cc.o
.PHONY : helloworld.cc.o

helloworld.i: helloworld.cc.i

.PHONY : helloworld.i

# target to preprocess a source file
helloworld.cc.i:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/helloworld.cc.i
.PHONY : helloworld.cc.i

helloworld.s: helloworld.cc.s

.PHONY : helloworld.s

# target to generate assembly for a file
helloworld.cc.s:
	$(MAKE) -f CMakeFiles/helloworld.dir/build.make CMakeFiles/helloworld.dir/helloworld.cc.s
.PHONY : helloworld.cc.s

helloworld_wrap.o: helloworld_wrap.cc.o

.PHONY : helloworld_wrap.o

# target to build an object file
helloworld_wrap.cc.o:
	$(MAKE) -f CMakeFiles/helloworld_wrap.dir/build.make CMakeFiles/helloworld_wrap.dir/helloworld_wrap.cc.o
.PHONY : helloworld_wrap.cc.o

helloworld_wrap.i: helloworld_wrap.cc.i

.PHONY : helloworld_wrap.i

# target to preprocess a source file
helloworld_wrap.cc.i:
	$(MAKE) -f CMakeFiles/helloworld_wrap.dir/build.make CMakeFiles/helloworld_wrap.dir/helloworld_wrap.cc.i
.PHONY : helloworld_wrap.cc.i

helloworld_wrap.s: helloworld_wrap.cc.s

.PHONY : helloworld_wrap.s

# target to generate assembly for a file
helloworld_wrap.cc.s:
	$(MAKE) -f CMakeFiles/helloworld_wrap.dir/build.make CMakeFiles/helloworld_wrap.dir/helloworld_wrap.cc.s
.PHONY : helloworld_wrap.cc.s

madness/mxm-summa.o: madness/mxm-summa.cc.o

.PHONY : madness/mxm-summa.o

# target to build an object file
madness/mxm-summa.cc.o:
	$(MAKE) -f CMakeFiles/mxm-summa-mad.dir/build.make CMakeFiles/mxm-summa-mad.dir/madness/mxm-summa.cc.o
.PHONY : madness/mxm-summa.cc.o

madness/mxm-summa.i: madness/mxm-summa.cc.i

.PHONY : madness/mxm-summa.i

# target to preprocess a source file
madness/mxm-summa.cc.i:
	$(MAKE) -f CMakeFiles/mxm-summa-mad.dir/build.make CMakeFiles/mxm-summa-mad.dir/madness/mxm-summa.cc.i
.PHONY : madness/mxm-summa.cc.i

madness/mxm-summa.s: madness/mxm-summa.cc.s

.PHONY : madness/mxm-summa.s

# target to generate assembly for a file
madness/mxm-summa.cc.s:
	$(MAKE) -f CMakeFiles/mxm-summa-mad.dir/build.make CMakeFiles/mxm-summa-mad.dir/madness/mxm-summa.cc.s
.PHONY : madness/mxm-summa.cc.s

madness/t9-wrap-ttg.o: madness/t9-wrap-ttg.cc.o

.PHONY : madness/t9-wrap-ttg.o

# target to build an object file
madness/t9-wrap-ttg.cc.o:
	$(MAKE) -f CMakeFiles/t9-wrap-mad.dir/build.make CMakeFiles/t9-wrap-mad.dir/madness/t9-wrap-ttg.cc.o
.PHONY : madness/t9-wrap-ttg.cc.o

madness/t9-wrap-ttg.i: madness/t9-wrap-ttg.cc.i

.PHONY : madness/t9-wrap-ttg.i

# target to preprocess a source file
madness/t9-wrap-ttg.cc.i:
	$(MAKE) -f CMakeFiles/t9-wrap-mad.dir/build.make CMakeFiles/t9-wrap-mad.dir/madness/t9-wrap-ttg.cc.i
.PHONY : madness/t9-wrap-ttg.cc.i

madness/t9-wrap-ttg.s: madness/t9-wrap-ttg.cc.s

.PHONY : madness/t9-wrap-ttg.s

# target to generate assembly for a file
madness/t9-wrap-ttg.cc.s:
	$(MAKE) -f CMakeFiles/t9-wrap-mad.dir/build.make CMakeFiles/t9-wrap-mad.dir/madness/t9-wrap-ttg.cc.s
.PHONY : madness/t9-wrap-ttg.cc.s

madness/ttg.o: madness/ttg.cc.o

.PHONY : madness/ttg.o

# target to build an object file
madness/ttg.cc.o:
	$(MAKE) -f CMakeFiles/ttgtest-mad.dir/build.make CMakeFiles/ttgtest-mad.dir/madness/ttg.cc.o
.PHONY : madness/ttg.cc.o

madness/ttg.i: madness/ttg.cc.i

.PHONY : madness/ttg.i

# target to preprocess a source file
madness/ttg.cc.i:
	$(MAKE) -f CMakeFiles/ttgtest-mad.dir/build.make CMakeFiles/ttgtest-mad.dir/madness/ttg.cc.i
.PHONY : madness/ttg.cc.i

madness/ttg.s: madness/ttg.cc.s

.PHONY : madness/ttg.s

# target to generate assembly for a file
madness/ttg.cc.s:
	$(MAKE) -f CMakeFiles/ttgtest-mad.dir/build.make CMakeFiles/ttgtest-mad.dir/madness/ttg.cc.s
.PHONY : madness/ttg.cc.s

mxm_simple_suma.o: mxm_simple_suma.cc.o

.PHONY : mxm_simple_suma.o

# target to build an object file
mxm_simple_suma.cc.o:
	$(MAKE) -f CMakeFiles/mxm_simple_suma.dir/build.make CMakeFiles/mxm_simple_suma.dir/mxm_simple_suma.cc.o
.PHONY : mxm_simple_suma.cc.o

mxm_simple_suma.i: mxm_simple_suma.cc.i

.PHONY : mxm_simple_suma.i

# target to preprocess a source file
mxm_simple_suma.cc.i:
	$(MAKE) -f CMakeFiles/mxm_simple_suma.dir/build.make CMakeFiles/mxm_simple_suma.dir/mxm_simple_suma.cc.i
.PHONY : mxm_simple_suma.cc.i

mxm_simple_suma.s: mxm_simple_suma.cc.s

.PHONY : mxm_simple_suma.s

# target to generate assembly for a file
mxm_simple_suma.cc.s:
	$(MAKE) -f CMakeFiles/mxm_simple_suma.dir/build.make CMakeFiles/mxm_simple_suma.dir/mxm_simple_suma.cc.s
.PHONY : mxm_simple_suma.cc.s

parsec/ttg.o: parsec/ttg.cc.o

.PHONY : parsec/ttg.o

# target to build an object file
parsec/ttg.cc.o:
	$(MAKE) -f CMakeFiles/ttgtest-parsec.dir/build.make CMakeFiles/ttgtest-parsec.dir/parsec/ttg.cc.o
.PHONY : parsec/ttg.cc.o

parsec/ttg.i: parsec/ttg.cc.i

.PHONY : parsec/ttg.i

# target to preprocess a source file
parsec/ttg.cc.i:
	$(MAKE) -f CMakeFiles/ttgtest-parsec.dir/build.make CMakeFiles/ttgtest-parsec.dir/parsec/ttg.cc.i
.PHONY : parsec/ttg.cc.i

parsec/ttg.s: parsec/ttg.cc.s

.PHONY : parsec/ttg.s

# target to generate assembly for a file
parsec/ttg.cc.s:
	$(MAKE) -f CMakeFiles/ttgtest-parsec.dir/build.make CMakeFiles/ttgtest-parsec.dir/parsec/ttg.cc.s
.PHONY : parsec/ttg.cc.s

t9-wrap.o: t9-wrap.cc.o

.PHONY : t9-wrap.o

# target to build an object file
t9-wrap.cc.o:
	$(MAKE) -f CMakeFiles/t9-wrap.dir/build.make CMakeFiles/t9-wrap.dir/t9-wrap.cc.o
.PHONY : t9-wrap.cc.o

t9-wrap.i: t9-wrap.cc.i

.PHONY : t9-wrap.i

# target to preprocess a source file
t9-wrap.cc.i:
	$(MAKE) -f CMakeFiles/t9-wrap.dir/build.make CMakeFiles/t9-wrap.dir/t9-wrap.cc.i
.PHONY : t9-wrap.cc.i

t9-wrap.s: t9-wrap.cc.s

.PHONY : t9-wrap.s

# target to generate assembly for a file
t9-wrap.cc.s:
	$(MAKE) -f CMakeFiles/t9-wrap.dir/build.make CMakeFiles/t9-wrap.dir/t9-wrap.cc.s
.PHONY : t9-wrap.cc.s

t9.o: t9.cc.o

.PHONY : t9.o

# target to build an object file
t9.cc.o:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/t9.cc.o
.PHONY : t9.cc.o

t9.i: t9.cc.i

.PHONY : t9.i

# target to preprocess a source file
t9.cc.i:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/t9.cc.i
.PHONY : t9.cc.i

t9.s: t9.cc.s

.PHONY : t9.s

# target to generate assembly for a file
t9.cc.s:
	$(MAKE) -f CMakeFiles/t9.dir/build.make CMakeFiles/t9.dir/t9.cc.s
.PHONY : t9.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... ttgtest-parsec"
	@echo "... install/local"
	@echo "... mxm-summa-mad"
	@echo "... install"
	@echo "... t9-wrap"
	@echo "... ttgtest-mad"
	@echo "... t9"
	@echo "... list_install_components"
	@echo "... helloworld"
	@echo "... mxm_simple_suma"
	@echo "... helloworld_wrap"
	@echo "... t9-wrap-mad"
	@echo "... helloworld.o"
	@echo "... helloworld.i"
	@echo "... helloworld.s"
	@echo "... helloworld_wrap.o"
	@echo "... helloworld_wrap.i"
	@echo "... helloworld_wrap.s"
	@echo "... madness/mxm-summa.o"
	@echo "... madness/mxm-summa.i"
	@echo "... madness/mxm-summa.s"
	@echo "... madness/t9-wrap-ttg.o"
	@echo "... madness/t9-wrap-ttg.i"
	@echo "... madness/t9-wrap-ttg.s"
	@echo "... madness/ttg.o"
	@echo "... madness/ttg.i"
	@echo "... madness/ttg.s"
	@echo "... mxm_simple_suma.o"
	@echo "... mxm_simple_suma.i"
	@echo "... mxm_simple_suma.s"
	@echo "... parsec/ttg.o"
	@echo "... parsec/ttg.i"
	@echo "... parsec/ttg.s"
	@echo "... t9-wrap.o"
	@echo "... t9-wrap.i"
	@echo "... t9-wrap.s"
	@echo "... t9.o"
	@echo "... t9.i"
	@echo "... t9.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

